- docs/getting-started.md
Updated the example of symphony CLI for WDK case and corrected the sample workflow by putting id.
> PLAT-11325: Updated documentation after supporting WDK in generator

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/connection/GetConnectionsExecutor.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/ConnectionsIntegrationTest.java
- workflow-bot-app/src/test/resources/connection/get-connections-no-params.swadl.yaml
- workflow-language/src/main/java/com/symphony/bdk/workflow/swadl/v1/activity/connection/GetConnections.java
- workflow-language/src/main/resources/swadl-schema-1.0.json
…d behaviour allowing the params to be null
> PLAT-11355: make get-connections support null params

- .github/pull_request_template.md
We do not always have a ticket to reference. Hence, the pull request template was updated for that
> PLAT-11374: Removed ticket reference from pull_request_template.md

- .gitignore
- README.md
- docs/reference.md
Updated documentation as workflow id becomes required.
Removed useless line from README.
Updated .gitignore to ignore data folder.
> PLAT-11372: Updated doc as workflow id becomes required.

- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/SendMessageIntegrationTest.java
We must mock the message service before starting the workflow
> Fix flaky test (for real!)

- build.gradle
- workflow-language/build.gradle
Bumped project version to 1.1.0-RC.
Updated workflow-language bdk bom version to latest as it was forgotten (only workflow-bot-app one was updated in master)
> Prepare release candidate rc-1

- build.gradle
- docs/concepts.md
- docs/examples/approval-form.swadl.yaml
- docs/reference.md
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/CamundaEngineConfiguration.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/CamundaExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/WorkflowEventToCamundaEvent.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/CamundaBpmnBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/SendMessageExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/UpdateMessageExecutor.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/DatafeedEventsIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/ExecuteScriptIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/FormReplyIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/IntegrationTest.java
- workflow-bot-app/src/test/resources/form/send-form-continuation.swadl.yaml
- workflow-bot-app/src/test/resources/form/send-form-loop.swadl.yaml
- workflow-bot-app/src/test/resources/form/send-form-unique-reply-timeout-following-activities.swadl.yaml
- workflow-bot-app/src/test/resources/form/send-form-unique-reply-timeout.swadl.yaml
- workflow-bot-app/src/test/resources/util/utility-functions-escape.swadl.yaml
- workflow-bot-app/src/test/resources/util/utility-functions-mentions.swadl.yaml
- workflow-bot-app/src/test/resources/util/utility-functions-text.swadl.yaml
- workflow-language/src/main/java/com/symphony/bdk/workflow/swadl/v1/activity/message/UpdateMessage.java
- workflow-language/src/main/java/com/symphony/bdk/workflow/swadl/v1/event/FormRepliedEvent.java
- workflow-language/src/main/resources/swadl-schema-1.0.json
> Preparing release 1.0.0-RC2

- README.md
- workflow-bot-app/build.gradle
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/WdkVersionLogger.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/configuration/VersionLogger.java
- workflow-bot-app/src/main/resources/application.yaml
Added a log of wdk version using Gradle resource filtering. A placehoder is added in spring application.yaml file that is replaced after the build with the current version.
Removed a disclaimer from README.
N/A
> PLAT-11870: Prepare GA release

- workflow-bot-app/build.gradle
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/group/AddGroupMemberExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/group/GetGroupsExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/group/UpdateGroupExecutor.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/GroupIntegrationTest.java
- workflow-language/build.gradle
BDK 2.7.0
Spring Boot 2.6.6
Jackson 2.13.2.20220328
To latest versions, should help with CVEs (although not applicable for
the WDK as the bot is running as a JAR)
> Upgrade BDK/Spring Boot

- docs/getting-started.md
Add instructions in documentation for how to update WDK
> Add instructions for how to update WDK

- docs/reference.md
- workflow-bot-app/src/test/resources/validation/validate-deploy.swadl.yaml
- workflow-bot-app/src/test/resources/validation/validate-only.swadl.yaml
- workflow-language/src/main/java/com/symphony/bdk/workflow/swadl/v1/Properties.java
- workflow-language/src/main/java/com/symphony/bdk/workflow/swadl/v1/Workflow.java
- workflow-language/src/main/resources/swadl-schema-1.0.json
Update json schema, use 'properties' instead of 'metadata'.
Add a reference doc to explain 'all-of' event list.
> Update json schema metadata field name to proerties

- build.gradle
Version bump to prepare release 1.2.0
> [RELEASE] 1.2.0: version bump

- build.gradle
Bump version to 1.3.0-SNAPSHOT after releasing 1.2.0
> Bump version to 1.3.0-SNAPSHOT after releasing 1.2.0

- docs/deployment.md
- postman/wdk.postman_collection.json
- workflow-bot-app/build.gradle
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/WorkflowsApiController.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/configuration/SwaggerConfiguration.java
- workflow-bot-app/src/main/resources/application.yaml
Introduced springfox swagger to document the WDK api.
The postman collection has been updated as well.
When running WDK, the documentation should be accessible on [http://localhost:8080/wdk/swagger-ui.html#](http://localhost:8080/wdk/swagger-ui.html#)
Added dependency for springfox swagger and swagger-ui 2
> Document WDK api

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/WorkflowsApi.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/WorkflowsApiController.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/dto/VariableView.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/configuration/WorkflowDeployer.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/converter/DefaultObjectConverter.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/converter/ObjectConverter.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/monitoring/converter/VariableDomainConverter.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/monitoring/repository/VariableCmdaApiQueryRepository.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/monitoring/repository/VariableQueryRepository.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/monitoring/service/MonitoringService.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/api/v1/WorkflowsApiControllerTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/configuration/WorkflowFolderWatcherTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/converter/DefaultObjectConverterTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/engine/WorkflowDirectGraphBuilderTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/engine/camunda/monitoring/converter/ActivityDomainConverterTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/engine/camunda/monitoring/converter/VariableDomainConverterTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/engine/camunda/monitoring/converter/WorkflowDomainConverterTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/engine/camunda/monitoring/converter/WorkflowInstanceDomainConverterTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/engine/camunda/monitoring/repository/ActivityCmdaApiQueryRepositoryTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/engine/camunda/monitoring/repository/VariableCmdaApiQueryRepositoryTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/engine/camunda/monitoring/repository/WorkflowCmdaApiQueryRepositoryTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/engine/camunda/monitoring/repository/WorkflowInstCmdaApiQueryRepositoryTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/monitoring/service/MonitoringServiceTest.java
> Add global variables endpoint

- docs/deployment.md
- workflow-bot-app/build.gradle
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/dto/WorkflowView.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/WorkflowDirectGraphBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/CamundaExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/monitoring/repository/WorkflowCmdaApiQueryRepository.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/monitoring/service/converter/WorkflowViewConverter.java
- workflow-bot-app/src/main/resources/application.yaml
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/api/v1/WorkflowsApiControllerTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/monitoring/service/converter/WorkflowViewConverterTest.java
- workflow-bot-app/src/test/resources/form/send-form-reply-nested.swadl.yaml
- workflow-bot-app/src/test/resources/form/send-form-reply.swadl.yaml
- workflow-bot-app/src/test/resources/monitoring/expected/list-workflows-response-payload.json
- workflow-language/src/main/java/com/symphony/bdk/workflow/swadl/v1/event/FormRepliedEvent.java
Update vulnerable dependency versions
Set FormRepliedEvent exclusivity default value to true
> Update dependencies to fix vulnerabilities

- workflow-bot-app/src/main/resources/application-local.yaml
> Remove local configuration from yaml

- build.gradle
Bump snapshot version after releasing WDK 1.3.0
> Bump snapshot version after releasing WDK 1.3.0

- custom-activity-example/build.gradle
Upgrade apache commons-text library to fix CVE-2022-42889.
> Mitigate CVE-2022-42889

- .github/workflows/build.yml
- .github/workflows/gradle-wrapper-validation.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- docs/reference.md
- workflow-bot-app/build.gradle
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/SendMessageExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/UpdateMessageExecutor.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/SendMessageIntegrationTest.java
- workflow-bot-app/src/test/resources/message/send-message-with-freemarker.swadl.yaml
- workflow-bot-app/src/test/resources/message/send-message-with-inline-template.swadl.yaml
- workflow-bot-app/src/test/resources/message/templates/message-freemarker.ftl
- workflow-bot-app/src/test/resources/message/update-message-template.swadl.yaml
- workflow-language/src/main/java/com/symphony/bdk/workflow/swadl/v1/activity/message/SendMessage.java
- workflow-language/src/main/java/com/symphony/bdk/workflow/swadl/v1/activity/message/UpdateMessage.java
Revert the inline template implementation from the last commit, because the feature is already supported out of box.
Still Keep the BDK version update and add an integration test to cover the inline template feature.
> Revert inline template implementation

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/WorkflowsMgtApi.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/exception/GlobalExceptionHandler.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/management/WorkflowAbstractAction.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/management/WorkflowDeployAction.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/management/WorkflowDeleteActionTest.java
Fix NPE while performing a delete action on a non-existing workflow.
Fix syntax bug on property injection.
> Fix delete action and property read bugs

- docs/concepts.md
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/DebugExecutor.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/DebugActivityIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/IntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/UpdateMessageIntegrationTest.java
- workflow-bot-app/src/test/resources/debug/debug-activity-outputs.swadl.yaml
- workflow-bot-app/src/test/resources/debug/debug-global-variables.swadl.yaml
- workflow-language/src/main/java/com/symphony/bdk/workflow/swadl/v1/activity/Debug.java
- workflow-language/src/main/resources/swadl-schema-1.0.json
Introduced Debug activity to be used to inspect object values in a SWADL. 
The debug activity does not require an Id in which case a random one is set.
> Standard debug Activity

- docs/concepts.md
- docs/reference.md
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/SpringBdkGateway.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/CamundaEngineConfiguration.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/UtilityFunctionsMapper.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/SendMessageExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/UpdateMessageExecutor.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/utils/UtilityFunctionsMapperTest.java
- workflow-language/src/main/java/com/symphony/bdk/workflow/engine/executor/BdkGateway.java
closes #198 
In this PR, we enriched the Utility functions with a new method allowing to retrieve the bot session info. For this purpose, a static sessionService field is added to the class, the SessionService bean is passed in the public constructor and set to the static field in order to be used in the static method session().
> #198 Expose Bot User Profile

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/WorkflowBotApplication.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/WorkflowsMgtApi.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/controller/WorkflowsMgtApiController.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/UpdateMessageExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/logs/LogsStreamingAppender.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/logs/LogsStreamingService.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/api/v1/controller/WorkflowsApiControllerTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/api/v1/controller/WorkflowsMgtApiControllerTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/logs/LogsStreamingAppenderTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/logs/LogsStreamingServiceTest.java
Client can subscribe to this endpoint to receive a streaming of WDK logs.
> Add a new SSE logs streaming endpoint

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/logs/LogsStreamingService.java
Use concurrent list instead, so make it thread safe.
> Use concurrent list

- postman/WDK_APIs.postman_collection.json
- postman/WDK_Environment.postman_environment.json
* Introduce environment file to accompany Postman collectioin
* Centralise monitoring and management token definition
* Add example SWADL to create and edit workflow endpoints
* Add example workflow and instance id's to fields
* Simplify date examples
> Improve Postman collection + environment

- postman/WDK_APIs.postman_collection.json
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/dto/SwadlView.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/management/WorkflowManagementService.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/management/WorkflowManagementServiceTest.java
Added a new field author to the validate and deploy endpoint. Updated postman collection and tests.
> Expose workflow author user id in deployment api

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/dto/WorkflowDefinitionView.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/monitoring/converter/AbstractInstanceDomainConverter.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/monitoring/converter/WorkflowInstDomainConverter.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/monitoring/converter/WorkflowInstDomainVersionConverter.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/monitoring/repository/WorkflowInstCmdaApiQueryRepository.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/management/WorkflowManagementService.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/MonitoringApiIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/engine/camunda/monitoring/converter/WorkflowInstDomainVersionConverterTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/engine/camunda/monitoring/repository/WorkflowInstCmdaApiQueryRepositoryTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/management/WorkflowManagementServiceTest.java
Some bugs detected in certain specific scenarios in monitoring service since the version has been involved.They are fixed in this commit.
> Fix bugs in monitoring service

- scripts/monitor.py
- scripts/simulate-processes.sh
Added performance profiling scripts
> Add performance profiling scripts

- deployment/config-map.yml
- deployment/deployment.yml
- deployment/persistence-volume-claims.yml
- deployment/secrets.yml
- deployment/service.yml
- deployment/volume-test.yml
- scripts/monitor.py
- scripts/simulate-processes.sh
Added GKE deployment files. Only used in this branch for the performance profiling experimentation.
> Added GKE deployment files

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/WorkflowsApi.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/exception/GlobalExceptionHandler.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/MonitoringApiIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/api/v1/controller/WorkflowsApiControllerTest.java
Fixes the monitoring api to make the token required.
> Fixes the monitoring api to make the token required

- Dockerfile
- workflow-bot-app/src/main/resources/application.yaml
Added missing java modules to the custom jre in order to make execute…-request activity works. Also put default datasource credentials in default application.yaml file.
> [CICD] - Added missing java modules to custom jre

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/WorkflowsMgtApi.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/controller/WorkflowsApiController.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/controller/WorkflowsMgtApiController.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/dto/SwadlView.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/dto/VersionedWorkflowView.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/dto/WorkflowView.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/CamundaEngine.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/CamundaBpmnBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/exception/GlobalExceptionHandler.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/management/WorkflowManagementService.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/management/converter/VersionedWorkflowBiConverter.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/management/converter/VersionedWorkflowConverter.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/monitoring/service/MonitoringService.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/monitoring/service/converter/VersionedWorkflowViewConverter.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/versioning/model/VersionedWorkflow.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/versioning/repository/VersionedWorkflowRepository.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/MonitoringApiIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/api/v1/controller/WorkflowsApiControllerTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/api/v1/controller/WorkflowsMgtApiControllerTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/exception/GlobalExceptionHandlerTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/management/WorkflowManagementServiceTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/management/converter/VersionedWorkflowConverterTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/monitoring/service/MonitoringServiceTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/monitoring/service/converter/VersionedWorkflowViewConverterTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/versioning/repository/VersionedWorkflowRepositoryTest.java
The author info of the workflow was missing in this endpoint payload, this commit add a new field 'createdBy', so the api client can refer it as the workflow's author.
> Add createdBy field to listWorkflows endpoint payload

- .github/workflows/release.yml
- Dockerfile
- allow-list.xml
- build.gradle
- docs/deployment-with-docker.md
- workflow-bot-app/build.gradle
> Push image to docker hub

- .github/workflows/release.yml
- build.gradle
- buildSrc/src/main/groovy/workflow-bot.java-conventions.gradle
- workflow-bot-app/build.gradle
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/WorkflowsMgtApi.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/controller/WorkflowsMgtApiController.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/api/v1/controller/WorkflowsMgtApiControllerTest.java
> Change the plugin to new version

- allow-list.xml
- build.gradle
- docs/reference.md
- workflow-bot-app/build.gradle
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/SendMessageExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/TemplateContentExtractor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/UpdateMessageExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/exception/GlobalExceptionHandler.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/MonitoringApiIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/api/v1/controller/ApiIntegrationTest.java
- workflow-bot-app/src/test/resources/message/send-message-with-freemarker.swadl.yaml
- workflow-bot-app/src/test/resources/message/send-message-with-inline-template.swadl.yaml
- workflow-bot-app/src/test/resources/message/update-message-template.swadl.yaml
- workflow-language/src/main/java/com/symphony/bdk/workflow/swadl/v1/activity/message/SendMessage.java
- workflow-language/src/main/java/com/symphony/bdk/workflow/swadl/v1/activity/message/UpdateMessage.java
> Bring the reverted inline template feature back

- build.gradle
Bump version to prepare the WDK 1.5.0 release
> release WDK 1.5.0

- build.gradle
Bump snapshot version in master branch after new release
> Bump snapshot version in master branch after new release

- docs/deployment-with-docker.md
- docs/deployment.md
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/configuration/WorkflowDataSourceConfiguration.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/CamundaEngineConfiguration.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/UtilityFunctionsMapper.java
- workflow-bot-app/src/main/resources/application-local.yaml
- workflow-bot-app/src/main/resources/application.yaml
Disk mode was not the default deployment mode by a mistake, this commit fix it.
> Revert the disk mode as default deployment mode

- allow-list.xml
- workflow-bot-app/build.gradle
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/WorkflowsApi.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/WorkflowsMgtApi.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/dto/SecretView.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/dto/SwadlView.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/secret/DefaultSecretKeeper.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/exception/GlobalExceptionHandler.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/api/v1/controller/WorkflowsMgtApiControllerTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/api/v1/controller/WorkflowsMgtApiIntegrationTest.java
- workflow-language/build.gradle
Secret created date was in wrong format. The error message was not correct when the secret key value is too long.
This commit fixed these bugs.
> Fix secret created date and error message bug

- docs/reference.md
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/builder/ActivityNodeBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/UpdateMessageExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/request/ExecuteRequestExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/event/V4ElementActionEventProcessor.java
- workflow-bot-app/src/main/resources/application.yaml
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/SecretIntegrationTest.java
- workflow-bot-app/src/test/resources/application-test.yaml
- workflow-bot-app/src/test/resources/secret/secret.swadl.yaml
- Fix bug when using update message back to back, the updated message id was read from the right variable list
- Fix exception missing in log issue, turns out the logger was truned off
- Fix request execution result body too long issue, truncate the body if the size is bigger than 1000.
- Update reference doc to better explain how to use template in a send message activity.
> Fix some bugs

- build.gradle
> Release v1.6.0

- workflow-bot-app/build.gradle
> Update BDK version

- Dockerfile
Closes #269 
Upgrade Dockerfile to Java 17
> Upgrade Dockerfile to Java 17

- .github/workflows/release.yml
- Dockerfile
- studio/Dockerfile
> Fix docker permissions

- workflow-bot-app/src/main/resources/application.yaml
Reduce actuator endpoint exposure to just health
> Reduce actuator endpoint exposure to just health

- .github/workflows/release.yml
- build.gradle
Bump version to 1.6.4
Upgrade federation client to 1.0.7
> Release v1.6.4

- .github/workflows/build.yml
- .github/workflows/cve-scanning-gradle.yml
- .github/workflows/gradle-wrapper-validation.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- allow-list.xml
- build.gradle
- buildSrc/src/main/groovy/workflow-bot.java-conventions.gradle
- studio/build.gradle
- workflow-bot-app/build.gradle
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/management/WorkflowManagementServiceTest.java
- workflow-language/build.gradle
> Update github action versions

- docs/devdocs/getting-started.md
- docs/devdocs/workflow-developer-kit.md
Added overview and get started from Symphony developer docs
> Docs overview
