finos/symphony-wdk

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/WorkflowsApiController.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/dto/ErrorResponse.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/dto/WorkflowExecutionRequest.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/CamundaEngine.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/api/v1/WorkflowsApiControllerIntegrationTest.java
- workflow-language/src/main/resources/swadl-schema-1.0.json
So we can eventually add error codes later, also easier to parse and
consistent with Spring errors.
---
Better deployment log 
Otherwise only the id (uuid) is printed.
---
Fix JSON schema for send-message.to.user-ids
Validation was broken with the empty enum.
Also do not assume how the args fields are named and use a placeholder.
> PLAT-11326: return errors as JSON and others mini fixes

- workflow-bot-app/build.gradle
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/RequestEventIntegrationTest.java
custom-activity-example module is not published on Maven central. workflow-bot-app having a dependency on it was making the project download fail.
For the same occasion, a small refactor in RequestEventsIntegrationTest for better readability.
> Removed dependency to custom-activity-example in workflow-bot-app

- buildSrc/src/main/groovy/workflow-bot.java-conventions.gradle
- workflow-language/build.gradle
The output of the workflow-bot-app module is the fatjar only, we don't
expect it to be a dependency from other projects, therefore we publish
the fatjar only.
> Publish only fatjar bot app

- docs/reference.md
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/SendMessageExecutor.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/SendMessageIntegrationTest.java
- workflow-bot-app/src/test/resources/message/send-blast-message.swadl.yaml
- workflow-language/src/main/java/com/symphony/bdk/workflow/swadl/v1/activity/SendMessage.java
- workflow-language/src/main/resources/swadl-schema-1.0.json
We can now send a message to multiple rooms with a single call to the
send-message activity (i.e. blast).
> Support blast messages in send-message

- docs/deployment.md
- docs/reference.md
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/CamundaEngineConfiguration.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/CamundaExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/CamundaBpmnBuilder.java
- workflow-bot-app/src/main/resources/application.yaml
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/ErrorIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/custom/assertion/WorkflowAssert.java
- workflow-bot-app/src/test/resources/application-test.yaml
- workflow-bot-app/src/test/resources/error/on-activity-failed-continue-failure.swadl.yaml
- workflow-bot-app/src/test/resources/error/on-activity-failed-continue.swadl.yaml
- workflow-bot-app/src/test/resources/error/on-activity-failed-continue2.swadl.yaml
- workflow-bot-app/src/test/resources/error/on-activity-failed-one-of.swadl.yaml
- workflow-bot-app/src/test/resources/error/on-activity-failed-retry.swadl.yaml
- workflow-bot-app/src/test/resources/error/on-activity-failed.swadl.yaml
- workflow-bot-app/src/test/resources/error/on-script-activity-failed.swadl.yaml
- workflow-language/src/main/java/com/symphony/bdk/workflow/swadl/v1/Event.java
- workflow-language/src/main/java/com/symphony/bdk/workflow/swadl/v1/event/ActivityFailedEvent.java
- workflow-language/src/main/resources/swadl-schema-1.0.json
Retries have been disabled at Camunda level, so a failing activity/task
only fails one and is not retried (was 3 times by default).
It is up to the workflow write to handle errors (the BDK also retries
when calling API, that can solve intermetting network issues for
instance).
An on.activity-failed event has been added to support that, it is
similar to the activity-expired or activity-completed event.
Using one-of, an error handler activity can be set for multiple
activities. Supporting a generic/catch all error handler was not easy to
implement and raise questions for complex flows or forms (what is the
scope of the error handling then?) so it is not supported for now.
Script task (execute-script) are a bit different so a bit of a hack had
to be used to make sure all exceptions are also …
> PLAT-11148: Error handling

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/room/CreateRoomExecutor.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/RoomIntegrationTest.java
- workflow-bot-app/src/test/resources/room/create-room-with-details-members.swadl.yaml
- workflow-bot-app/src/test/resources/room/create-room-with-details.swadl.yaml
- workflow-language/src/main/java/com/symphony/bdk/workflow/swadl/v1/activity/room/CreateRoom.java
In a previous commit, we added some fields that were missing in create-room activity such as memberCanInvite... Or, these fields were only added in the pojo and swadl-schema and were not used in the executor.
In this commit we made use of them in the executor and updated the tests
> Made use of all fields in create-room

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/CamundaEngine.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/WorkflowEventToCamundaEvent.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/CamundaBpmnBuilder.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/RequestReceivedEventIntegrationTest.java
- workflow-bot-app/src/test/resources/event/request-received2.swadl.yaml
- workflow-language/src/main/java/com/symphony/bdk/workflow/swadl/v1/event/RequestReceivedEvent.java
If multiple workflows are listening to request-received-event they would
all get triggered because the signal's name is the same for all
workflows.
Making the workflow id part of the signal name solves this issue.
> Handle multiple workflows/request-received-event

- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/ISSUE_TEMPLATE/Support_question.md
- .github/ISSUE_TEMPLATE/meeting_minutes.md
- .github/pull_request_template.md
- NOTICE
- README.md
Related ticket: [PLAT-11374](https://perzoinc.atlassian.net/browse/PLAT-11374)
Steps required by https://odp.finos.org/docs/project-collaboration/#finos-project-blueprint:
> PLAT-11374 - Apply FINOS Software Project Blueprint

- buildSrc/src/main/groovy/workflow-bot.java-conventions.gradle
As we are moving to Finos, we would like to publish Maven artifacts
under the Finos group.
> Publish Maven artifacts under org.finos group

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/configuration/WorkflowFolderWatcher.java
Now that the workflow id is required, when a swadl file is changed, the previous deployed version is not used anymore for new executions but only for pending ones. For this reason, WorkflowFolderWatcher does not need anymore to undeploy a workflow when the file changed. Calling undeploy method is still required when a swadl file is deleted.
> PLAT-11372: remove undeploy

- docs/reference.md
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/PinMessageExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/UnpinMessageExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/UpdateMessageExecutor.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/PinUnpinMessageIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/UpdateMessageIntegrationTest.java
- workflow-bot-app/src/test/resources/message/pin-message.swadl.yaml
- workflow-bot-app/src/test/resources/message/unpin-message.swadl.yaml
- workflow-language/src/main/java/com/symphony/bdk/workflow/swadl/v1/activity/message/PinMessage.java
- workflow-language/src/main/java/com/symphony/bdk/workflow/swadl/v1/activity/message/UnpinMessage.java
- workflow-language/src/main/resources/swadl-schema-1.0.json
Goal of this implementation is to add support for pin/unpin messages activities. The following activities have been implemented:
```
- pin-message:
id: pinMessage
message-id: messageId
```
```
- unpin-message:
id: unpinMessage
stream-id: streamId
```
Closes https://github.com/finos/symphony-wdk/issues/46
> PLAT-11470 Support pin/unpin messages

- buildSrc/src/main/groovy/workflow-bot.java-conventions.gradle
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/variable/BpmnToAndFromBaseActivityMixin.java
- workflow-language/src/main/java/com/symphony/bdk/workflow/swadl/v1/activity/BaseActivity.java
Javadoc is currently failing and preventing deploying on Maven Central.
Fixed the issues (<p> tags) and made it run along the check tasks so we
avoid merging incorrect javadoc.
Also disabled Javadoc warnings as we don't need to address them
(sometimes we are better off with no @return/@throws if we have nothing
interesting to comment).
> Fix javadoc generation

- docs/reference.md
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/request/RequestExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/request/client/HttpClient.java
When sending a multipart/form request, the content type should include the boundary. However, this is no something the user can set in SWADL.
In this commit, we changed the way we handle this content type request and we made use of MultipartEntityBuilder that sets the boundary along with the content type in body.
When the content type is provided in the header than it overrides the one set by MultipartEntityBuilder. For this reason, when we process a multipart/form request, we remove the content type from headers if the user has provided any in order to make use of the one set with boundary.
> PLAT-11536 Fixed multipart content type.

- buildSrc/src/main/groovy/workflow-bot.java-conventions.gradle
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/CamundaExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/SendMessageExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/UpdateMessageExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/request/RequestExecutor.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/SendMessageIntegrationTest.java
- workflow-bot-app/src/test/resources/com/symphony/bdk/workflow/configuration/workflow.swadl.yaml
- workflow-language/src/main/java/com/symphony/bdk/workflow/engine/executor/ActivityExecutorContext.java
Related to [PLAT-11517](https://perzoinc.atlassian.net/browse/PLAT-11517)
Some activities have more than one output variable to store in the context. Outputs are stored in an outer map having one item key called outputs, and the value is an inner map storing the actual variables. The method setOutputVariable() that was used for that was handling one variable at a time. When it is called a second time to store the second variable, then it was creating a new outer map with outputs key before setting the actual variable which overrides the previosu output in the context. In this commit, we refactored that with a method that takes a map of outputs and store them in one shot.
An output might be null, so we use a Hashmap and update it by putting outputs one bye one instead of doing it in one …
> PLAT-11517: Activity outputs are overridden

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/CamundaBpmnBuilder.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/EventTypesIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/SendMessageIntegrationTest.java
- workflow-bot-app/src/test/resources/event/timeout/activity-expired-leading-to-new-branch.swadl.yaml
[PLAT-11535](https://perzoinc.atlassian.net/browse/PLAT-11535)
In a previous PR we added the support of timeouts with the main process and we added the possibility to connect the timed out activities to a dedicated activity. This latter is executed when the specified one/ones is/are timed out. However, this implementation did not allow to connect a branch (a part of workflow) to activities with time out. Only one acitivty could be connected.
The issue was that when we have an activity with on:acitivty-expired property, we move the builder backward to the specified activity having timeout property in order to connect the two activities, but we do not update the builder with the new one. Thus, the following activities are added to the end of the workflow.
With this implementation, having an …
> PLAT-11535: Support timeout.

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/CamundaExecutor.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/DatafeedEventsIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/GetAttachmentIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/IntegrationTest.java
- workflow-bot-app/src/test/resources/event/event-middle-using-outputs.swadl.yaml
In #69, we created the outputs outer map using Map.of() that creates an immutable map. This map was supposed to be read only as a new instance is created at the end of every activity, and we never update it. To update an output we create a new instance of the map.
This introduced a new bug in the ProcessEngine. When an event comes to the workflow, the ProcessEngine deserializes the context outputs, and this fails when the map storing context outputs is immutable. The error could not be found on basic workflows that have one event to start it, as at the beginning no immutable map is created in the context yet. However, with events in the middle of the workflows, an immutable map is already found in the context and outputs deserialization fails with …
> Fixed Deserialization bug on immutable collection storing workflows outputs

- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/custom/assertion/WorkflowAssert.java
PR checks are sometimes failing. I'm not 100% sure but maybe even if the
process is marked as completed all the historic details (like vars) have
not yet been written to the DB.
So we wait (actively) for that when checking variables.
> Fix flaky test sendMessageOnMessage

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/CamundaExecutor.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/LoopIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/custom/assertion/WorkflowAssert.java
- workflow-bot-app/src/test/resources/loop/loop-overrides-outputs.swadl.yaml
In #69, we fixed a bug about activities outputs being overridden when an activity has multiple outputs to store. We implemented a sanity method called before writing outputs to check no outputs already exist  for that activity in the context. In this case, a runtime exception is thrown.
When we use loops, an activity is called multiple times and then, in the same process, the activity writes its outputs multiple times. This was not accepted anymore because of that sanity check. We removed it in this commit.
A small change is done in the WorkflowAssert: when an activity is executed multiple times, only the last execution outputs are kept in the context. But the method we use to test outputs use a history details which returns all outputs. We were getting the first occurence which does not …
> Bug fix: activity outputs should be overridden when the activity is called multiple time

- buildSrc/build.gradle
- buildSrc/src/main/groovy/workflow-bot.java-conventions.gradle
- spotbugs.xml
- workflow-bot-app/build.gradle
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/PinMessageExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/UnpinMessageExecutor.java
- workflow-language/build.gradle
Java BDK 2.4.3 (using Spring Boot 2.6.1)
We can now remove escaping on message/thread ids.
Upgrade other dependencies too, sometime removing the number so we can
rely on the BDK/Spring Boot BOM.
> Upgrade dependencies

- workflow-bot-app/build.gradle
- workflow-language/build.gradle
Use latest release of BDK
Force to latest release of Spring Boot (once BDK uses it we can remove
it)
Force Jackson, Rhino versions too to address vulnerabilities
There is one left about h2 but we cannot fix it for now, see #89
> Upgrade dependencies (BDK, Spring Boot)

- workflow-bot-app/build.gradle
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/WorkflowEventToCamundaEvent.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/CamundaBpmnBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/variable/FormVariableListener.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/FormReplyIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/custom/assertion/WorkflowAssert.java
- workflow-bot-app/src/test/resources/form/send-form-outputs-are-preserved.swadl.yaml
- workflow-bot-app/src/test/resources/form/send-form-reply-followup-activity-exclusive.swadl.yaml
Because we set the process variable under the same name (activity
id/form id) than the activity outputs for instance, we are overwriting
them when receiving a form reply.
Instead we now store them in a different name, just pass them with the
message that is triggering a form reply activity and with an execution
listener we properly merge them with existing variables like outputs.
This way we don't break the existing API.
N/A
- [-] Referenced a ticket in the PR title or description
> Avoid overwriting activity outputs with form replies

- docs/reference.md
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/CamundaEngineConfiguration.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/UtilityFunctionsMapper.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/SendMessageExecutor.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/SendMessageIntegrationTest.java
- workflow-bot-app/src/test/resources/message/send-message-with-freemarker.swadl.yaml
- workflow-bot-app/src/test/resources/message/templates/message-freemarker.ftl
We can now use functions such as text,emojis,... im templates directly.
This is supported by adding a new 'wdk' object in the freemarker
variables on which methods can be called:
${wdk.text(...)}
Fixes #95
N/A
> Support utility functions in templates

- docs/reference.md
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/UtilityFunctionsMapper.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/request/ExecuteRequestExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/request/ExecuteRequestUtils.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/ExecuteRequestIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/custom/assertion/WorkflowAssert.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/utils/ExecuteRequestUtilsTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/utils/UtilityFunctionsMapperTest.java
- workflow-bot-app/src/test/resources/request/execute-request-encode-query-parameters.swadl.yaml
- workflow-bot-app/src/test/resources/request/execute-request-not-encode-query-parameters-no-response.swadl.yaml
- workflow-bot-app/src/test/resources/request/execute-request-not-encode-query-parameters.swadl.yaml
- workflow-language/src/main/java/com/symphony/bdk/workflow/swadl/v1/activity/request/ExecuteRequest.java
- workflow-language/src/main/resources/swadl-schema-1.0.json
Since the execute-request activity takes the full URL as input and does not handle query parameters separately, the encoding/decoding should be the responsibility of the workflow and not the activity itself. The utility methods are added to be used in execute-script.
encodeRawQuery() only encodes the query parameters and does not change the other components.
closes #106
> Added encodeRawQuery and decodeRawQuery to encode/decode url query parameters

- build.gradle
Bump snapshot to 1.2.0-SNAPSHOT following 1.1.0 release.
The last time we released 1.0.0, we forgot to bump the snapshot, that's why here we go from 1.0.0-SNAPSHOT to 1.2.0-SNAPSHOT.
> Bump snapshot

- .whitesource.config
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/FormReplyIntegrationTest.java
Having whitesource config mode set to LOCAL, a local whitesource.config was required, otherwise the scan times out.
This configuration excludes dependencies for test configurations.
For more info: https://whitesource.atlassian.net/wiki/spaces/WD/pages/1544880156/Unified+Agent+Configuration+Parameters
> Added local whitesource config

- docs/reference.md
- workflow-bot-app/build.gradle
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/UpdateMessageExecutor.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/FormReplyIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/UpdateMessageIntegrationTest.java
- workflow-bot-app/src/test/resources/message/update-notsilent-message.swadl.yaml
- workflow-language/build.gradle
- workflow-language/src/main/java/com/symphony/bdk/workflow/swadl/v1/activity/message/UpdateMessage.java
- workflow-language/src/main/resources/swadl-schema-1.0.json
The silent flag in the update message service was included
in the new BDK release, this commit is to support the same
in WDK.
> Add silent flag to update message activity

- .whitesource
- .whitesource.config
Set whitesource config mode to AUTO. LOCAL mode does not work even with a local whitesource config file.
> Set whitesource config mode to AUTO.

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/WorkflowEventToCamundaEvent.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/builder/FormRepliedNodeBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/builder/JoinActivityNodeBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/builder/SignalNodeBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/variable/FormVariableListener.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/SendMessageExecutor.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/IntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/JoinIntegrationTest.java
- workflow-bot-app/src/test/resources/graph/form-reply-all-of.swadl.yaml
Form reply event in a all-of list is construct as a message
element and it must be exclusive without having a timeout constrait,
otherwise it does not make sense in this particular use case.
> Fix bug when form reply event in allOf list

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/BpmnBuilderHelper.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/CamundaBpmnBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/builder/FormRepliedNodeBuilder.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/RequestReceivedEventIntegrationTest.java
- workflow-bot-app/src/test/resources/event/request-received-in-one-of-with-form-replied-activity.swadl.yaml
- workflow-bot-app/src/test/resources/event/request-received-in-one-of.swadl.yaml
#149 
The issue happens when the workflow has an activity with triggering event request-received within one-of property that sends a form, and a subsequent activity executed on that form replied. The workflow being built has this request-received event attached to an endEvent which makes the workflow completes once the request is received without executing the activities. The issue comes from an incomplete condition checking if the activity is in a loop. We enriched this condition by checking if the current activity is of type ACTIVITY_COMPLETED_EVENT.
**Before the fix:**
**After the fix:**
> #149: Fix bug when on request-received event is added with a subsequent activity having form-replied event.

- docs/reference.md
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/dto/WorkflowActivitiesView.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/dto/WorkflowDefinitionView.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/WorkflowDirectGraph.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/WorkflowDirectGraphBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/CamundaExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/monitoring/repository/VariableCmdaApiQueryRepository.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/SendMessageExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/monitoring/repository/VariableQueryRepository.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/monitoring/service/MonitoringService.java
- workflow-bot-app/src/main/resources/application-local.yaml
- workflow-bot-app/src/main/resources/application.yaml
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/ErrorIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/IntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/MonitoringApiIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/SendMessageIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/api/v1/WorkflowsApiControllerTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/engine/WorkflowDirectGraphBuilderTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/engine/camunda/monitoring/repository/VariableCmdaApiQueryRepositoryTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/monitoring/service/MonitoringServiceTest.java
- workflow-bot-app/src/test/resources/message/send-message-on-message.swadl.yaml
- workflow-language/src/main/java/com/symphony/bdk/workflow/engine/executor/ActivityExecutorContext.java
- workflow-language/src/main/java/com/symphony/bdk/workflow/swadl/v1/activity/message/SendMessage.java
- workflow-language/src/main/resources/swadl-schema-1.0.json
- Add a new data field to SendMessage activity to support interative templates
- Add errors field to activity API, show error message if the process fails due to un-handled exception
close #150
> Add data field to SendMessage activity

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/WorkflowDirectGraphBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/WorkflowNode.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/BpmnBuilderHelper.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/CamundaBpmnBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/builder/AbstractNodeBpmnBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/builder/ActivityExpiredNodeBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/builder/FormRepliedNodeBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/builder/SignalNodeBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/UpdateMessageExecutor.java
- workflow-bot-app/src/main/resources/application.yaml
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/FormReplyIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/JoinIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/MonitoringApiIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/engine/WorkflowDirectGraphBuilderTest.java
Revert back to the original solution for exclusive FormRepliedEvent. Using subprocess is too much complex to handle the form reply use cases we can have right now.
close #152 
> Use message component for exclusive form reply event

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/dto/TaskDefinitionView.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/dto/TaskTypeEnum.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/monitoring/service/MonitoringService.java
- workflow-bot-app/src/main/resources/application.yaml
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/MonitoringApiIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/api/v1/WorkflowsApiControllerTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/monitoring/service/MonitoringServiceTest.java
This split make it easier to distinguish the workflow node's type and group for UI to build up the component for nodes.
close #165 
> Split current workflow node type into type and group

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/WorkflowDirectGraphBuilder.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/MonitoringApiIntegrationTest.java
- workflow-bot-app/src/test/resources/monitoring/testing-workflow-definition.swadl.yaml
The bug is a regression following the change, in which we reverted the solution for an exclusive FormRepliedEvent not using camunda subprocess.
The NPE happens on the timeout event coming along with a form reply event, this extra event is automatically generated and was mising the event type.
The fix is to set the event type when this event is created.
> Fix NPE bug in a definition having a FormRepliedEvent

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/WorkflowValidator.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/WorkflowDirectGraphBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/builder/FormRepliedNodeBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/variable/FormVariableListener.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/monitoring/service/MonitoringService.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/JoinIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/MonitoringApiIntegrationTest.java
- workflow-bot-app/src/test/resources/monitoring/allof-on-activities-definition.swadl.yaml
A FormRepliedEvent was not allowed to be start event in a workflow. With this commit, this becomes possible, if user has already a form defined in the room, the workflow is now able to catch the form reply to start a  workflow instance.
> Make FormRepliedEvent as a start event

- docs/reference.md
- workflow-bot-app/build.gradle
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/SendMessageExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/UpdateMessageExecutor.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/SendMessageIntegrationTest.java
- workflow-bot-app/src/test/resources/message/send-message-with-inline-template.swadl.yaml
- workflow-bot-app/src/test/resources/message/update-message-template.swadl.yaml
- workflow-language/src/main/java/com/symphony/bdk/workflow/swadl/v1/activity/message/SendMessage.java
- workflow-language/src/main/java/com/symphony/bdk/workflow/swadl/v1/activity/message/UpdateMessage.java
- workflow-language/src/main/resources/swadl-schema-1.0.json
Add inline template support, the field "template" now is holding the inline template string, the field "template-path" is used for the template file.
> Add inline template support for message activity

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/room/GetRoomsExecutor.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/RoomIntegrationTest.java
- workflow-bot-app/src/test/resources/room/get-rooms-bad-pagination-no-limit.swadl.yaml
- workflow-bot-app/src/test/resources/room/get-rooms-bad-pagination-no-skip.swadl.yaml
- workflow-bot-app/src/test/resources/room/obo/get-rooms-obo-bad-pagination-no-limit.swadl.yaml
- workflow-bot-app/src/test/resources/room/obo/get-rooms-obo-bad-pagination-no-skip.swadl.yaml
In get rooms executor, the criteria were wrong where an owner or member id is set because the creator id was used rather. This has been fixed in this PR, more tests are added to improve the coverage and avoid such issues in the future
Closes #211
> #211 Fix Get rooms wrong criteria

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/SendMessageExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/event/AbstractRealTimeEventProcessor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/event/V4ElementActionEventProcessor.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/EventIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/FormReplyIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/IntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/RequestReceivedEventIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/SendMessageIntegrationTest.java
- workflow-bot-app/src/test/resources/form/send-blast-form-reply.swadl.yaml
- workflow-bot-app/src/test/resources/form/send-two-forms-same-id.swadl.yaml
In this PR, we added the support of blast form replies.
Having an activity to be executed on a form reply event, if this form has been sent in a blast way, then the activity triggers only when the first form is replied and not the other blast ones.
When a blast message is sent, we only store the first messageId in outputs. This is stored as a variable of the ongoing process instances. 
In the form reply event processing class, we only execute ongoing processes that have a variable msgId equals to the message id of the form that has been actioned. So when the messageId is not the one that is stored in the variable, the process is not executed. 
The fix consists of introducing a new output variable msgIds to the SendMessageExecutor where we store the list of message ids in case of a blast, …
> Support blast form replies

- allow-list.xml
- build.gradle
- buildSrc/build.gradle
- postman/Symphony Workflow Developer Kit (WDK) APIs.postman_collection.json
- workflow-bot-app/build.gradle
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/WorkflowsMgtApi.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/controller/WorkflowsMgtApiController.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/dto/SwadlView.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/dto/VersionedWorkflowView.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/management/WorkflowManagementService.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/management/converter/VersionedWorkflowConverter.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/versioning/repository/VersionedWorkflowRepository.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/api/v1/controller/WorkflowsMgtApiControllerTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/management/WorkflowManagementServiceTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/management/converter/VersionedWorkflowConverterTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/versioning/repository/VersionedWorkflowRepositoryTest.java
This is a follow up work on version control feature, add version awareness to the management api, so a specific version of workflow can be retrieved, redeployed and deleted.
> Add version awareness to the management api

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/event/V4ElementActionEventProcessor.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/FormReplyIntegrationTest.java
- workflow-bot-app/src/test/resources/form/send-form-reply-starting-event.swadl.yaml
When no ongoing process is found for the formid and the form replied event messageId, we need to only execute startMessageOnly which is the only case where not finding a pending process is expected, otherwise no process should be executed. 
The exception thrown by Camunda is catched and logged as it is expected and should not make the workflow to fail.
> Fix blast form replied event for start messages

- workflow-bot-app/src/main/resources/application-local.yaml
- workflow-bot-app/src/main/resources/application.yaml
When an activity execution starts, the NodeBuilder stores its swadl as String in order to allow CamundaExecutor to read it and build the activity to be executed. The insert query is not executed on the fly but only after the execution ends, as a batch. When the activity swadl exceeds 4000 char, the insert query batch fails as the variable is of type String requiring a max of 4000 chars. This exception cannot be caught in WDK as it is executed by a Camunda scheduled job. The exception does not make the workflow to fail but only logs the stacktrace. As the variable only used by the CamundaExecutor, and it is not fetched after the activity execution, we decided to only hide it from the console by setting the log level of org.camunda.bpm to OFF.
> Disable org.camunda.bpm log to avoid Camunda stacktrace

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/monitoring/repository/WorkflowInstCmdaApiQueryRepository.java
When a version parameter is provided, the list instances management api was not removing entries with unmatching versions, the converter was setting null as version for those unmatching instances. This is due to the fact that the processDefinitionKey, which is the workflow id, was used for filtering. This has been replaced by the processDefinitionId which is the id of the matching versions instances.
> Fix versions filter in the instances management api

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/exception/GlobalExceptionHandler.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/management/WorkflowManagementService.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/exception/GlobalExceptionHandlerTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/management/WorkflowManagementServiceTest.java
The error message returned when trying to update a workflow that has an already published version was confusing at it says that the workflow does not exist. Ths has been fixed in this PR by firstly checking if the workflow exists, then returning a more detailed exception when a version is already published.
> Fix response code when trying to update a published workflow

- .github/workflows/release.yml
- Dockerfile
#226 
The docker image push job depends on the release job but it needs to checkout the repository when it starts which makes it lose the fatJar procuded by the previous job. In this commit, we added actions to the release job to download the fatJar as an artifact and download it in the next job to create the docker image.
> [CICD] - Fixed Docker image push job in the release workflow

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/CamundaEngine.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/event/DatafeedEventToWorkflowEvent.java
Since BDK 2.13.0, the RealTimeEvent object is actually a sub type of the original V4 event type, therefore change the Spring event listener method signature to include the sub type of the event.
It is also a good practice to include the sub type to have maximum extensibility in the code.
> Fix event listener method signature bug

- allow-list.xml
- docs/reference.md
- workflow-bot-app/build.gradle
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/configuration/WorkflowDataSourceConfiguration.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/CamundaEngineConfiguration.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/CamundaExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/UtilityFunctionsMapper.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/message/TemplateContentExtractor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/shared/DefaultSharedDataStore.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/shared/SharedData.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/shared/SharedDataRepository.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/versioning/model/VersionedWorkflow.java
- workflow-bot-app/src/main/resources/application-local.yaml
- workflow-bot-app/src/main/resources/application.yaml
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/SharedDataIntegrationTest.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/utils/UtilityFunctionsMapperTest.java
- workflow-bot-app/src/test/resources/shareddata/shared-counter-data.swadl.yaml
- workflow-bot-app/src/test/resources/shareddata/shared-counter-data2.swadl.yaml
- workflow-language/src/main/java/com/symphony/bdk/workflow/engine/executor/ActivityExecutorContext.java
- workflow-language/src/main/java/com/symphony/bdk/workflow/engine/executor/SharedDataStore.java
Create a shared data store, so that the shared data is accessible among the process instances and also among the different workflows.
The shared data is grouped by its namespace, the key of the data must be unique in its namespace, but could be duplicate in different namespace.
> Add new functional mapper to create a shared data store

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/logs/LogsStreamingAppender.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/logs/LogsStreamingAppenderTest.java
The log streaming appender was only adding exceptions formatted message. As the stacktrace can help troubleshooting, we added the stacktrace lines to the streamed payload.
> Add exceptions stack trace to the log streaming appender.

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/versioning/BigStringCompressor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/versioning/model/VersionedWorkflow.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/swadl/CompressionTest.java
Add Spring Jpa attribute converter to compress and decompress the swadl attribute string, in order to save storage.
> Compress the swadl string to save storage

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/CamundaEngine.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/CamundaBpmnBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/builder/FormRepliedNodeBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/builder/WorkflowNodeBpmnBuilderRegistry.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/event/EventVisitor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/event/WorkflowEventType.java
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/TimerEventsIntegrationTest.java
- workflow-bot-app/src/test/resources/event/timer/timer-multiple-at.swadl.yaml
- workflow-language/src/main/resources/swadl-schema-1.0.json
A map is used to register the events and activities in the workflow graph, timer fired event uses a fixed string as id, in case there is several multi timers, the latest one overwrites the previous ones.
This commit fixed the issue by appending timer value to the event name, so they should be unique most of time, except if the timer value is the same (work around is to use all-of).
> Fix issue to support multi timer fired event

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/api/v1/dto/SecretView.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/event/V4MessageSentEventProcessor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/logs/LogsStreamingAppender.java
- workflow-bot-app/src/main/resources/application.yaml
- workflow-bot-app/src/test/java/com/symphony/bdk/workflow/logs/LogsStreamingAppenderTest.java
The exception message was missing in the log appender. This commit fix the bug by using the Logback ThrowableProxyUtil to parse the stacktrace into string, so all info about the exception is in the final string.
> Fix exception message missing bug

- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/CamundaExecutor.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/CamundaBpmnBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/builder/AbstractNodeBpmnBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/builder/ActivityExpiredNodeBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/builder/ActivityFailedNodeBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/builder/ActivityNodeBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/builder/JoinActivityNodeBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/camunda/bpmn/builder/WorkflowNodeBpmnBuilder.java
- workflow-bot-app/src/main/java/com/symphony/bdk/workflow/engine/executor/request/ExecuteRequestExecutor.java
The activity json string input variable might be too big to be stored in DB (4000 characters limit), e.g. the activity json string contains a variable being resolved at runtime with a more than 4000 characters string value, when camunda persists this new activity json string as variable in DB, it fails with an exception.
This commit fixed this issue by definiting the input activity string in a map instead of string, the map object is stored in bytearray table as BLOB type without limit.
> Fix activity variable size limit bug
